# Sample OpenShift BuildConfig to enable the OpenShift to build this container image and push to a 
# remote registry (docker.io/jgregmac/misp-modules:latest is this example).
# A deploykey for pushing the image would need to be present in the secret "deploykey-misp-modules".

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: misp-modules
  namespace: misp-test
  labels:
    app: misp
    component: modules
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker.io/jgregmac/misp-modules:latest'
    pushSecret:
      name: harbor-robot
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'git@github.com:YaleDevSecOps/misp-modules.git'
      ref: main
    contextDir: /
    sourceSecret:
      name: deploykey-misp-modules
  triggers:
    - type: ConfigChange
  runPolicy: Serial